### PR TITLE
Version 0.10

### PR DESCRIPTION
**Pull request by vbarrielle**
I think the round of refactoring for 0.10 is complete now, I can't think of some more breaking changes we might want to add. So I think I'm going to publish 0.10 soon. @mulimoen do you see something I could have forgotten?

### CODE REVIEW

**Comment by vbarrielle** [comment]
CI failures are expected, I have not pushed `sprs` 0.10 to crates.io, so the dependent crates cannot find it...

**Comment by mulimoen** [comment]
> CI failures are expected, I have not pushed sprs 0.10 to crates.io, so the dependent crates cannot find it...

I think you were just missing a couple of bumps. Let's see if we got them all now

**Comment by vbarrielle** [comment]
Good catch!

**Comment by mulimoen** [comment]
I can't think of any additional breaking changes we need going forwards. I say we publish!

**Comment by vbarrielle** [comment]
It's published! :tada:

**Pull request merged**
