### PR TITLE
use same version of dependencies

### PR DESCRIPTION
**Pull request by mulimoen**
This ensures all dependencies are the same version

### CODE REVIEW

**Comment by vbarrielle** [comment]
Good idea, with the upcoming 0.10 it's the good moment to introduce changes in dependencies versions. Looks like there's a rusftmt issue though.

**Comment by vbarrielle** [comment]
Looking at the failure, it's an issue I've encountered for #245, and it's fixed there. It's caused by a change in rustmft with the latest rust release. Re-running the tests should work.

**Comment by vbarrielle** [comment]
No I'm wrong, it needs to be rebased. Alternatively, I can merge it like this, and the merge result should pass the rustfmt test.

**Comment by mulimoen** [comment]
I've rebased on master now

**Comment by vbarrielle** [comment]
Perfect, thanks!

**Pull request merged**
